# Permalinks
permalink:           pretty

# Setup
title:               SpiffyCoffee
tagline:             Hello! 
description:         >
    # floating in the ethernet 
url:                 http://www.spiffycoffee.com
paginate:            5
paginate_path:       "/blog/page:num/" 
baseurl:             ""

# Photo gallery
collections:
  photography:
    output: true

defaults:
  - scope:
      path: ""
      type: photography
    values:
      layout: photo

# Assets
sass:
  style:            :compressed

# About/contact
author:
  name:              Philip Xie 
  url:               https://twitter.com/spiffycoffee
  email:             philip@spiffycoffee.com

# Custom vars
version:             2.1.0
github:
  repo:              https://github.com/poole/hyde

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
